version: "3.8"

services:
    postgres:
      image: postgres:14.7
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: '2G'
      restart: always
      ports:
        - "5432:5432"
      environment:
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=my_store

    pgadmin:
      image: dpage/pgadmin4
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: '2G'
      environment:
        PGADMIN_DEFAULT_EMAIL: "root@mail.com"
        PGADMIN_DEFAULT_PASSWORD: "root"
      ports:
        - "5050:80"
      depends_on:
        - postgres
